### ISSUE TITLE
Dev Rel Migration

### ISSUE THREAD

**Issue by wanderingbort** [eosnetworkfoundation/engineering#67]
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/engineering/issues/59
- [ ] https://github.com/eosnetworkfoundation/engineering/issues/56
- [ ] https://github.com/eosnetworkfoundation/devhub/issues/22
```
